### ISSUE TITLE
.NET 6 Target with Assembly Trimming

### ISSUE THREAD

**Issue by ds5678** [Sewer56/Sewer56.BitStream#3]
[Trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming) allows for smaller apps to be compiled.

**Comment by Sewer56** [comment]
Should be done; was trivial as this library doesn't use any patterns unhealthy to trimming. 
I have already been trimming a few of my libraries lately so this is naturally par for the course.
